chitika_plugin:
  chitika_publisher_code:
    client: true
    default: ''
  chitika_show_topiclist_top:
    client: true
    default: false
  chitika_show_topic_top:
    client: true
    default: false
  chitika_show_topic_bottom:
    client: true
    default: false
  chitika_through_trust_level:
    client: true
    default: 2
